# A collection of modules/configurations for a hyprland-based desktop environment

{
  pkgs,
  osConfig,
  config,
  lib,
  ...
}:

let
  cfg = config.modules.hyprland;
in

with lib;
{
  options.modules.hyprland = {
    enable = mkEnableOption "hyprland desktop environment";

  };
  imports = [
    ./lookandfeel.nix
    ./hyprpaper.nix # wallpaper
    ./bindings
    ./waybar
  ];
  config = mkIf cfg.enable {

    # some default apps referenced in config
    programs.foot.enable = true;

    services.mako = {
      enable = true;
      settings = {
        default-timeout = 5 * 1000;

        # theme-specific settings handled by stylix
        padding = 10;
        border-size = 2;
        border-radius = 4;
        max-icon-size = 32;
      };
    };
    programs.rofi = {
      enable = true;
      package = pkgs.rofi-wayland;
    };

    wayland.windowManager.hyprland = {
      enable = true;

      # avoid conflict with uwsm setup
      systemd.enable = false;

      # basic config just to get things started
      # mostly taken from the autogenerated config

      settings = {

        # MONITORS
        monitor = ",preferred,auto,1";

        # MY PROGRAMS
        # TODO: manage this better
        "$terminal" = "foot";
        # "$fileManager" = "dolphin";
        "$menu" = "rofi -terminal=$terminal -show drun";

        # AUTOSTART
        exec-once = [
          # TODO:

          # "uwsm-app -- mako"
        ];

        # ENVIRONMENT VARIABLES
        env = [
          "XCURSOR_SIZE,24"
          "HYPRCURSOR_SIZE,24"
        ];

      };
    };

  };
}
