# A collection of modules/configurations for a hyprland-based desktop environment

{
  pkgs,
  osConfig,
  config,
  lib,
  ...
}:

let
  cfg = config.modules.hyprland;

  # master toggle
  enable = osConfig.programs.hyprland.enable;
in

with lib;
{
  options.modules.hyprland = {

  };
  imports =
    [ ]
    # conditional imports
    ++ (optionals (enable) [
      ./swayosd.nix
      ./waybar.nix
    ]);
  config = mkIf osConfig.modules.hyprland.enable {

    wayland.windowManager.hyprland = {
      enable = true;

      # avoid conflict with uwsm setup
      systemd.enable = false;

      # basic config just to get things started
      # mostly taken from the autogenerated config

      settings = {

        # MONITORS
        monitor = ",preferred,auto,auto";

        # MY PROGRAMS
        # TODO: manage this better
        "$terminal" = "foot";
        # "$fileManager" = "dolphin";
        "$menu" = "wofi --term=$terminal --show drun";

        # AUTOSTART
        exec-once = [
          # TODO:
        ];

        # ENVIRONMENT VARIABLES
        env = [
          "XCURSOR_SIZE,24"
          "HYPRCURSOR_SIZE,24"
        ];

        # LOOK AND FEEL
        general = {
          gaps_in = "4";
          gaps_out = "10";

          border_size = "1";

          # TODO: setup colorschemes
          "col.active_border" = "rgba(33ccffee) rgba(00ff99ee) 45deg";
          "col.inactive_border" = "rgba(595959aa)";

          # toggle to resize windows by clicking and dragging borders/gaps
          resize_on_border = "false";

          allow_tearing = "false";

          layout = "dwindle";
        };

        decoration = {
          rounding = "3";
          rounding_power = "3";

          active_opacity = "1.0";
          inactive_opacity = "1.0";

          shadow = {
            enabled = "true";
            range = "4";
            render_power = "3";
            color = "rgba(1a1a1aee)";
          };

          blur = {
            enabled = "true";
            size = "3";
            passes = "1";

            vibrancy = "0.1696";
          };
        };

        # defaults from autogenerated
        # TODO: learn what all of this is
        animations = {
          enabled = "yes, please :)";

          bezier = [
            "easeOutQuint, 0.23,1,0.32,1"
            "easeInOutCubic,0.65,0.05,0.36,1"
            "linear,0,0,1,1"
            "almostLinear,0.5,0.5,0.75,1.0"
            "quick,0.15,0,0.1,1"
          ];

          animation = [
            "global, 1, 10, default"
            "border, 1, 5.39, easeOutQuint"
            "windows, 1, 4.79, easeOutQuint"
            "windowsIn, 1, 4.1, easeOutQuint, popin 87%"
            "windowsOut, 1, 1.49, linear, popin 87%"
            "fadeIn, 1, 1.73, almostLinear"
            "fadeOut, 1, 1.46, almostLinear"
            "fade, 1, 3.03, quick"
            "layers, 1, 3.81, easeOutQuint"
            "layersIn, 1, 4, easeOutQuint, fade"
            "layersOut, 1, 1.5, linear, fade"
            "fadeLayersIn, 1, 1.79, almostLinear"
            "fadeLayersOut, 1, 1.39, almostLinear"
            "workspaces, 1, 1.94, almostLinear, fade"
            "workspacesIn, 1, 1.21, almostLinear, fade"
            "workspacesOut, 1, 1.94, almostLinear, fade"
          ];
        };

        # https://wiki.hyprland.org/Configuring/Dwindle-Layout/
        dwindle = {
          pseudotile = "true";
          preserve_split = "true";
        };

        # INPUT
        input = {
          kb_layout = "us";
          follow_mouse = "1";
          sensitivity = "0"; # -1.0 - 1.0, 0 is default

          touchpad = {
            natural_scroll = "false";
          };
        };

        # KEYBINDINGS
        "$mod" = "SUPER"; # Windows key

        bindm = [
          # mouse movements
          "$mod, mouse:272, movewindow"
          "$mod, mouse:273, resizewindow"
          "$mod ALT, mouse:272, resizewindow"
        ];

        bind = [
          "$mod, RETURN, exec, $terminal"
          "$mod, W, killactive,"
          "$mod, V, togglefloating,"
          "$mod, SPACE, exec, $menu"
          "$mod, P, pseudo," # dwindle
          "$mod, S, togglesplit," # dwindle

          # move focus with mod + arrows/hjkl
          "$mod, left, movefocus, l"
          "$mod, H, movefocus, l"
          "$mod, right, movefocus, r"
          "$mod, L, movefocus, r"
          "$mod, up, movefocus, u"
          "$mod, K, movefocus, u"
          "$mod, down, movefocus, d"
          "$mod, J, movefocus, d"

          # change workspace with mod+0-9
          "$mod, 1, workspace, 1"
          "$mod, 2, workspace, 2"
          "$mod, 3, workspace, 3"
          "$mod, 4, workspace, 4"
          "$mod, 5, workspace, 5"
          "$mod, 6, workspace, 6"
          "$mod, 7, workspace, 7"
          "$mod, 8, workspace, 8"
          "$mod, 9, workspace, 9"
          "$mod, 0, workspace, 10"

          # move active to a workspace with mod+shift+0-9
          "$mod SHIFT, 1, movetoworkspace, 1"
          "$mod SHIFT, 2, movetoworkspace, 2"
          "$mod SHIFT, 3, movetoworkspace, 3"
          "$mod SHIFT, 4, movetoworkspace, 4"
          "$mod SHIFT, 5, movetoworkspace, 5"
          "$mod SHIFT, 6, movetoworkspace, 6"
          "$mod SHIFT, 7, movetoworkspace, 7"
          "$mod SHIFT, 8, movetoworkspace, 8"
          "$mod SHIFT, 9, movetoworkspace, 9"
          "$mod SHIFT, 0, movetoworkspace, 10"

          # scroll through workspaces with mod+scroll
          "$mod, mouse_down, workspace, e+1"
          "$mod, mouse_up, workspace, e-1"

        ];
      };
    };

  };
}
