{ pkgs, lib, ... }:

with lib;
{
  wayland.windowManager.hyprland = {
    settings = {
      general = {
        gaps_in = "4";
        gaps_out = "10";

        border_size = "1";

        # toggle to resize windows by clicking and dragging borders/gaps
        resize_on_border = "false";

        allow_tearing = "false";

        layout = "dwindle";
      };

      decoration = {
        rounding = "3";
        rounding_power = "3";

        active_opacity = "1.0";
        inactive_opacity = "1.0";

        shadow = {
          enabled = "true";
          range = "4";
          render_power = "3";
          color = mkDefault "rgba(1a1a1aee)";
        };

        blur = {
          enabled = "true";
          size = "3";
          passes = "1";

          vibrancy = "0.1696";
        };
      };

      # defaults from autogenerated
      # TODO: learn what all of this is
      animations = {
        enabled = "yes, please :)";

        bezier = [
          "easeOutQuint, 0.23,1,0.32,1"
          "easeInOutCubic,0.65,0.05,0.36,1"
          "linear,0,0,1,1"
          "almostLinear,0.5,0.5,0.75,1.0"
          "quick,0.15,0,0.1,1"
        ];

        animation = [
          "global, 1, 10, default"
          "border, 1, 5.39, easeOutQuint"
          "windows, 1, 4.79, easeOutQuint"
          "windowsIn, 1, 4.1, easeOutQuint, popin 87%"
          "windowsOut, 1, 1.49, linear, popin 87%"
          "fadeIn, 1, 1.73, almostLinear"
          "fadeOut, 1, 1.46, almostLinear"
          "fade, 1, 3.03, quick"
          "layers, 1, 3.81, easeOutQuint"
          "layersIn, 1, 4, easeOutQuint, fade"
          "layersOut, 1, 1.5, linear, fade"
          "fadeLayersIn, 1, 1.79, almostLinear"
          "fadeLayersOut, 1, 1.39, almostLinear"
          "workspaces, 1, 1.94, almostLinear, fade"
          "workspacesIn, 1, 1.21, almostLinear, fade"
          "workspacesOut, 1, 1.94, almostLinear, fade"
        ];
      };

      # https://wiki.hyprland.org/Configuring/Dwindle-Layout/
      dwindle = {
        pseudotile = "true";
        preserve_split = "true";
      };

      # INPUT
      input = {
        kb_layout = "us";
        follow_mouse = "1";
        sensitivity = "0"; # -1.0 - 1.0, 0 is default

        touchpad = {
          natural_scroll = "false";
        };
      };
    };
  };
}
