name: Update NixOS Flake

on:
  schedule:
    - cron: "0 0 * * 0" # Runs at midnight (00:00) on Sundays
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main # Adjust if your default branch has a different name

      - name: Set up Nix
        uses: cachix/install-nix-action@v21

      - name: Update Nix flake
        run: |
          nix flake update --commit-lock-file
        env:
          GIT_AUTHOR_NAME: "GitHub Actions"
          GIT_AUTHOR_EMAIL: "actions@github.com"
          GIT_COMMITTER_NAME: "GitHub Actions"
          GIT_COMMITTER_EMAIL: "actions@github.com"

      - name: Push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:refs/heads/update-flake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token for authentication

      - name: Create a Pull Request
        if: github.event_name == 'schedule'
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Update flake.lock"
          body: "Automated update of flake.lock file by GitHub Actions"
          base: main # Adjust if your default branch has a different name
          branch: update-flake
