name: Update NixOS Flake

on:
  schedule:
    - cron: "0 0 * * 0" # Runs at midnight (00:00) on Sundays
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main # Adjust if your default branch has a different name

      - name: Set up Nix
        uses: cachix/install-nix-action@v21

      - name: Update Nix flake
        run: |
          nix flake update --commit-lock-file
        env:
          GIT_AUTHOR_NAME: "GitHub Actions"
          GIT_AUTHOR_EMAIL: "actions@github.com"
          GIT_COMMITTER_NAME: "GitHub Actions"
          GIT_COMMITTER_EMAIL: "actions@github.com"

      - name: Fetch latest changes from origin
        run: git fetch origin

      - name: Rebase update-flake branch onto main
        run: |
          git checkout -B update-flake
          git rebase origin/main

      - name: Force push rebased branch
        run: |
          git push --force-with-lease origin update-flake
        env:
          GIT_AUTHOR_NAME: "GitHub Actions"
          GIT_AUTHOR_EMAIL: "actions@github.com"
          GIT_COMMITTER_NAME: "GitHub Actions"
          GIT_COMMITTER_EMAIL: "actions@github.com"

      - name: Create or update Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Update flake.lock"
          body: "Automated update of flake.lock file by GitHub Actions"
          base: main # Adjust if your default branch has a different name
          branch: update-flake
